sudo: required

branches:
  except:
  - master

language:
  - node_js

node_js:
  - "12.18.1"

# services:
#   - docker

stages:
  - Tests

before_install:
  - yarn install

jobs:
  include:
    - stage: "Tests"
      name: "Tests"
      script:
        # run tests
        - yarn test -u
        - yarn test --coverage
        - ./node_modules/.bin/codecov -t ${CODECOV_MOBILE_TOKEN}