sudo: required

language:
  - node_js
  - python

node_js:
  - "12.18.1"

python:
  - "3.8"

stages:
  - Tests
  - Upload APK to slack

before_install:
  - pip3 install --upgrade pip

install:
  - yarn install
  - pip install slack_sdk

jobs:
  include:
    - stage: "Tests"
      name: "Tests"
      script:
        # run tests
        - yarn test --coverage
        - ./node_modules/.bin/codecov -t ${CODECOV_MOBILE_TOKEN}

    - stage: "Upload APK to slack"
      name: "Upload APK to slack"
      if: (NOT type IN (pull_request)) AND branch = feature/112-continuous-delivey
      script:
        - yarn android-release
        - python3 ./scripts/slack.py